version: '2.3'
services:
  # No cache
  
  nocache-X:
    image: pcic/ncwms-mm-rproxy:i5-improve-caching
    container_name: "ncwms-mm-rproxy-nocache-X"
    ports:
      - "30510:8000"
    environment:
      - MM_DSN
      - FLASK_LOGLEVEL=INFO
      - GUNICORN_WORKERS=1
      - GUNICORN_WORKER_CLASS=sync
    volumes:
      - type: bind
        source: ./flask.config.nocache.py
        target: /app/ncwms_mm_rproxy/flask.config.py
        read_only: true

  nocache-A:
    image: pcic/ncwms-mm-rproxy:i5-improve-caching
    container_name: "ncwms-mm-rproxy-nocache-A"
    ports:
      - "30511:8000"
    environment:
      - MM_DSN
      - FLASK_LOGLEVEL=INFO
      - GUNICORN_WORKERS=10
      - GUNICORN_WORKER_CLASS=sync
    volumes:
      - type: bind
        source: ./flask.config.nocache.py
        target: /app/ncwms_mm_rproxy/flask.config.py
        read_only: true

  nocache-B:
    image: pcic/ncwms-mm-rproxy:i5-improve-caching
    container_name: "ncwms-mm-rproxy-nocache-B"
    ports:
      - "30512:8000"
    environment:
      - MM_DSN
      - FLASK_LOGLEVEL=INFO
      - GUNICORN_WORKERS=1
      - GUNICORN_WORKER_CLASS=gevent
      - GUNICORN_WORKER_CONNECTIONS=10
    volumes:
      - type: bind
        source: ./flask.config.nocache.py
        target: /app/ncwms_mm_rproxy/flask.config.py
        read_only: true

  nocache-C:
    image: pcic/ncwms-mm-rproxy:i5-improve-caching
    container_name: "ncwms-mm-rproxy-nocache-C"
    ports:
      - "30513:8000"
    environment:
      - MM_DSN
      - FLASK_LOGLEVEL=INFO
      - GUNICORN_WORKERS=10
      - GUNICORN_WORKER_CLASS=gevent
      - GUNICORN_WORKER_CONNECTIONS=10
    volumes:
      - type: bind
        source: ./flask.config.nocache.py
        target: /app/ncwms_mm_rproxy/flask.config.py
        read_only: true

  nocache-D:
    image: pcic/ncwms-mm-rproxy:i5-improve-caching
    container_name: "ncwms-mm-rproxy-nocache-D"
    ports:
      - "30514:8000"
    environment:
      - MM_DSN
      - FLASK_LOGLEVEL=INFO
      - GUNICORN_WORKERS=1
      - GUNICORN_WORKER_CLASS=gthread
      - GUNICORN_THREADS=10
    volumes:
      - type: bind
        source: ./flask.config.nocache.py
        target: /app/ncwms_mm_rproxy/flask.config.py
        read_only: true

  nocache-E:
    image: pcic/ncwms-mm-rproxy:i5-improve-caching
    container_name: "ncwms-mm-rproxy-nocache-E"
    ports:
      - "30515:8000"
    environment:
      - MM_DSN
      - FLASK_LOGLEVEL=INFO
      - GUNICORN_WORKERS=1
      - GUNICORN_WORKER_CLASS=gthread
      - GUNICORN_THREADS=10
    volumes:
      - type: bind
        source: ./flask.config.nocache.py
        target: /app/ncwms_mm_rproxy/flask.config.py
        read_only: true

  # dict cache

  dictcache-X:
    image: pcic/ncwms-mm-rproxy:i5-improve-caching
    container_name: "ncwms-mm-rproxy-dictcache-X"
    ports:
      - "30520:8000"
    environment:
      - MM_DSN
      - FLASK_LOGLEVEL=INFO
      - GUNICORN_WORKERS=1
      - GUNICORN_WORKER_CLASS=sync
    volumes:
      - type: bind
        source: ./flask.config.dictcache.py
        target: /app/ncwms_mm_rproxy/flask.config.py
        read_only: true

  dictcache-A:
    image: pcic/ncwms-mm-rproxy:i5-improve-caching
    container_name: "ncwms-mm-rproxy-dictcache-A"
    ports:
      - "30521:8000"
    environment:
      - MM_DSN
      - FLASK_LOGLEVEL=INFO
      - GUNICORN_WORKERS=10
      - GUNICORN_WORKER_CLASS=sync
    volumes:
      - type: bind
        source: ./flask.config.dictcache.py
        target: /app/ncwms_mm_rproxy/flask.config.py
        read_only: true

  dictcache-B:
    image: pcic/ncwms-mm-rproxy:i5-improve-caching
    container_name: "ncwms-mm-rproxy-dictcache-B"
    ports:
      - "30522:8000"
    environment:
      - MM_DSN
      - FLASK_LOGLEVEL=INFO
      - GUNICORN_WORKERS=1
      - GUNICORN_WORKER_CLASS=gevent
      - GUNICORN_WORKER_CONNECTIONS=10
    volumes:
      - type: bind
        source: ./flask.config.dictcache.py
        target: /app/ncwms_mm_rproxy/flask.config.py
        read_only: true

  dictcache-C:
    image: pcic/ncwms-mm-rproxy:i5-improve-caching
    container_name: "ncwms-mm-rproxy-dictcache-C"
    ports:
      - "30523:8000"
    environment:
      - MM_DSN
      - FLASK_LOGLEVEL=INFO
      - GUNICORN_WORKERS=10
      - GUNICORN_WORKER_CLASS=gevent
      - GUNICORN_WORKER_CONNECTIONS=10
    volumes:
      - type: bind
        source: ./flask.config.dictcache.py
        target: /app/ncwms_mm_rproxy/flask.config.py
        read_only: true

  dictcache-D:
    image: pcic/ncwms-mm-rproxy:i5-improve-caching
    container_name: "ncwms-mm-rproxy-dictcache-D"
    ports:
      - "30524:8000"
    environment:
      - MM_DSN
      - FLASK_LOGLEVEL=INFO
      - GUNICORN_WORKERS=1
      - GUNICORN_WORKER_CLASS=gthread
      - GUNICORN_THREADS=10
    volumes:
      - type: bind
        source: ./flask.config.dictcache.py
        target: /app/ncwms_mm_rproxy/flask.config.py
        read_only: true

  dictcache-E:
    image: pcic/ncwms-mm-rproxy:i5-improve-caching
    container_name: "ncwms-mm-rproxy-dictcache-E"
    ports:
      - "30525:8000"
    environment:
      - MM_DSN
      - FLASK_LOGLEVEL=INFO
      - GUNICORN_WORKERS=1
      - GUNICORN_WORKER_CLASS=gthread
      - GUNICORN_THREADS=10
    volumes:
      - type: bind
        source: ./flask.config.dictcache.py
        target: /app/ncwms_mm_rproxy/flask.config.py
        read_only: true

networks:
  default:
    external:
      name: pcicbr0